#!/bin/sh
# If using normal root, avoid changing anything.
if [ -z "$RPM_BUILD_ROOT" -o "$RPM_BUILD_ROOT" = "/" ]; then
	exit 0
fi

if [ `uname` = SunOS ]; then
    strip_flags=""
else
    strip_flags="--strip-unneeded"
fi

# Strip ELF binaries
for f in `find $RPM_BUILD_ROOT -type f -exec file {} \; | \
	grep -v ' shared object,' | \
	sed -n -e 's/^\(.*\):[ 	]*ELF.*, not stripped/\1/p'`; do
	strip $strip_flags $f || :
done

# Strip ELF shared objects
# Please note we don't restrict our search to executable files because
# our libraries are not (should not be, at least) +x.
for f in `find $RPM_BUILD_ROOT -type f -a -exec file {} \; | \
	grep ' shared object,' | \
	sed -n -e 's/^\(.*\):[ 	]*ELF.*, not stripped/\1/p'`; do
	strip $strip_flags $f || :
done

# Strip .comment and .note sections (the latter only if it is not allocated)
# for already stripped elf files in the build root
if [ `uname` = SunOS ]; then
    exit 0;
fi

for f in `find $RPM_BUILD_ROOT -type f \( -perm -0100 -or -perm -0010 -or -perm -0001 \) -exec file {} \; | \
	sed -n -e 's/^\(.*\):[ 	]*ELF.*, stripped/\1/p'`; do
	note="-R .note"
	if objdump -h $f | grep '^[ 	]*[0-9]*[ 	]*.note[ 	]' -A 1 | \
		grep ALLOC >/dev/null; then
		note=
	fi
	strip -R .comment $note $f || :
done

