#!/usr/bin/perl -w

# Copyright 2003 Ximian, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

use strict;

use FindBin;
use lib "$FindBin::RealBin/../lib";

use Ximian::Util ':all';

use Ximian::BB::XML;

sub usage {
    print STDERR <<EOF;
usage: bb_xmlgen [options] input
    input is one of:
\tan RPM specfile
\ta debian control file
\ta tarball
    options:
\t-h, --help\thelp
EOF
    exit 1;
}

my %args;
parse_args
    (\%args,
     [
      {names => ["help", "?", "h"], run => \&usage},
     ]);

my $input = $ARGV[0];
usage unless ($input);

my $xml = new Ximian::BB::XML ($input);

print Ximian::BB::XML::write($xml);
